apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb-app
spec:
  selector:
    app: influxdb-app
  ports:
    - port: 8086
      protocol: TCP
      name: influxdb
  type: ClusterIP