apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress-app
spec:
  selector:
    matchLabels:
      app: wordpress-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      restartPolicy: Always
      containers:
      - image: wordpress-img
        name: wordpress
        ports:
        - containerPort: 5050
          name: http
        imagePullPolicy: Never
        env:
        - name: DB_NAME
          valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db_name
        - name: DB_USER
          valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db_user
        - name: DB_HOST
          valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db_host
        - name: DB_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db-password