apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deploy
  labels:
    app: telegraf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf-app
    spec:
      restartPolicy: Always
      containers:
      - image: telegraf-img
        name: telegraf
        ports:
        - containerPort: 8125
          name: telegraf
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        env:
          - name: INFLUXDB_DB
            valueFrom:
              secretKeyRef:
                name: telegraf-secret
                key: influxdb_db
          - name: INFLUXDB_URL
            valueFrom:
              secretKeyRef:
                name: telegraf-secret
                key: influxdb_url
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: influxdb_admin_user
          - name: INFLUXDB_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: influxdb_admin_password
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock