CREATE USER 'DB_USER'@'%' IDENTIFIED BY 'DB_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'DB_USER'@'%' WITH GRANT OPTION;
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON wordpress.* TO 'DB_USER'@'%' IDENTIFIED BY 'DB_PASSWORD';
DROP DATABASE test;
FLUSH PRIVILEGES;