apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin-app
spec:
  selector:
    app: phpmyadmin-app
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  type: LoadBalancer