apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-vol-clm
  labels:
    app: ftps-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
spec:
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: ftps-img:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
        - containerPort: 21006
        - containerPort: 21007
        - containerPort: 21008
        - containerPort: 21009
        - containerPort: 21010
        env:
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: ftps_user
        - name: FTP_PASS
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: ftps_pass
        livenessProbe:
          exec:
            command:
            - sh
            - livenessprobe.sh
          initialDelaySeconds: 15
          periodSeconds: 3
        volumeMounts:
        - name: ftps-vol
          mountPath: /ftps
      volumes:
      - name: ftps-vol
        persistentVolumeClaim:
          claimName: ftps-vol-clm
