apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress-app
spec:
  selector:
    app: wordpress-app
  ports:
    - port: 5050
      targetPort: 5050
      name: http
  type: LoadBalancer