apiVersion: v1
kind: Service
metadata:
  name: telegraf-svc
  labels:
    app: telegraf-app
spec:
  selector:
    app: telegraf-app
  ports:
    - port: 8125
      protocol: TCP
      name: telegraf
  type: ClusterIP