apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps-app
spec:
  selector:
    app: ftps-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: ftps-control
    port: 21
    targetPort: 21
  - name: ftps-data
    port: 20
    targetPort: 20
  - name: ftps-pasv-21000
    port: 21000
    targetPort: 21000
  - name: ftps-pasv-21001
    port: 21001
    targetPort: 21001
  - name: ftps-pasv-21002
    port: 21002
    targetPort: 21002
  - name: ftps-pasv-21003
    port: 21003
    targetPort: 21003
  - name: ftps-pasv-21004
    port: 21004
    targetPort: 21004
  - name: ftps-pasv-21005
    port: 21005
    targetPort: 21005
  - name: ftps-pasv-21006
    port: 21006
    targetPort: 21006
  - name: ftps-pasv-21007
    port: 21007
    targetPort: 21007
  - name: ftps-pasv-21008
    port: 21008
    targetPort: 21008
  - name: ftps-pasv-21009
    port: 21009
    targetPort: 21009
  - name: ftps-pasv-21010
    port: 21010
    targetPort: 21010
